# Here we can store "secrets" things, that we don't want to be viewd from everyone on github or from the user of the application
#ATTENZIONE: QUESTA PAGINA DOVREBBE NON ESSERE VERDE E NON AVERE LA "U" A DESTRA

# User info
username="Pippo"
password="DV4S!"

[further secrets]
secrets_username="Caruso"
secret_password="password!"